# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" # New: Specific check day
      time: "09:00" # New: Time in UTC
    allow:
      - dependency-name: "rails"
      - dependency-name: "rspec*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)" # New: Separate prefix for dev deps
    open-pull-requests-limit: 5
    reviewers: # New: Auto-assign reviewers
      - "sergey-arkhipov"
    labels: # New: Auto-label PRs
      - "dependencies"
